id: A6E8AB93E
base_file: f73E8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:58:56.440367
  last_modified_at: 2022-05-31 04:58:56.440375
