id: A6E8AB93E
base_file: f743E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:58:56.443133
  last_modified_at: 2022-05-31 04:58:56.443137
